import { FeedItem, MonitorCanvas, ExploreSearch } from './types';

export const existingSearches: ExploreSearch[] = [
  { id: '1', name: 'Brand + Earnings Risk', category: 'Brand' },
  { id: '2', name: 'Regulatory & Policy Mentions', category: 'Policy' },
  { id: '3', name: 'Executive Leadership Coverage', category: 'Leadership' },
  { id: '4', name: 'Industry Layoffs & Restructuring', category: 'Leadership' },
  { id: '5', name: 'Brand Sentiment Watch', category: 'Brand' },
  { id: '6', name: 'M&A and Acquisition Activity', category: 'Competition' },
  { id: '7', name: 'Social Backlash Monitoring', category: 'Social' },
  { id: '8', name: 'Competitor Product Launches', category: 'Competition' },
];

const generateFeedItems = (searchName: string): FeedItem[] => {
  const feedTemplates: Record<string, FeedItem[]> = {
    'Brand + Earnings Risk': [
      {
        id: '1-1',
        source: 'Financial Times',
        author: 'Sarah Johnson',
        timestamp: '15m ago',
        title: 'Q4 Earnings Preview: Tech Giants Face Headwinds',
        content: 'Analysts are closely watching upcoming earnings reports as market volatility continues. Key metrics to watch include revenue guidance and cost management initiatives.',
        reach: 125000,
        sentiment: 'neutral',
        mediaType: 'news',
      },
      {
        id: '1-2',
        source: 'Bloomberg',
        author: 'Michael Chen',
        timestamp: '32m ago',
        title: 'Brand Value Rankings Show Surprising Shifts',
        content: 'The latest brand value index reveals significant movement among top companies, with tech firms seeing both gains and losses in consumer perception.',
        reach: 89000,
        sentiment: 'positive',
        mediaType: 'news',
      },
      {
        id: '1-3',
        source: 'MarketWatch',
        handle: '@mktwatch_pro',
        timestamp: 'Today · 2:45 PM',
        content: 'Major brand earnings risk emerging as Q4 results disappoint across the sector. Investors are pulling back on brand-heavy portfolios heading into the next quarter.',
        reach: 8200,
        sentiment: 'negative',
        mediaType: 'social',
        platform: 'X',
        country: 'US',
        keyword: 'brand earnings',
        likes: 14,
        views: 312,
      },
      {
        id: '1-4',
        source: 'Bloomberg Radio',
        timestamp: 'Today · 1:15 PM',
        title: 'Bloomberg Radio — Fri, 17 Apr 2026 13:15:00 -0500',
        content: 'We\'re seeing unprecedented brand volatility in this earnings season. Risk analysts at major firms are watching closely as companies report their Q4 results.',
        reach: 45000,
        sentiment: 'neutral',
        mediaType: 'radio',
        platform: 'Radio',
        country: 'US',
        keyword: 'brand',
        audioDuration: '8:30',
      },
      {
        id: '1-5',
        source: 'Reuters',
        author: 'Emma Williams',
        timestamp: '1h ago',
        title: 'Market Reacts to Earnings Guidance',
        content: 'Stock prices fluctuated after several major companies revised their earnings outlook for the upcoming quarter.',
        reach: 67000,
        sentiment: 'negative',
        mediaType: 'news',
      },
    ],
    'Executive Leadership Coverage': [
      {
        id: '2-1',
        source: 'Wall Street Journal',
        author: 'David Park',
        timestamp: '45m ago',
        title: 'CEO Spotlight: Leadership Transitions in Tech',
        content: 'A wave of leadership changes is reshaping the technology sector, with several high-profile CEO appointments announced this week.',
        reach: 98000,
        sentiment: 'neutral',
        mediaType: 'news',
      },
      {
        id: '2-2',
        source: 'CNBC',
        author: 'Lisa Thompson',
        timestamp: '2h ago',
        title: 'Executive Pay Debates Continue',
        content: 'Shareholder activism is putting pressure on compensation committees as discussions around executive pay intensify.',
        reach: 54000,
        sentiment: 'negative',
        mediaType: 'news',
      },
      {
        id: '2-3',
        source: 'Forbes',
        author: 'James Miller',
        timestamp: '3h ago',
        title: 'Top Leaders Share Vision for 2026',
        content: 'Industry executives outline their strategic priorities, focusing on AI integration and sustainable growth.',
        reach: 72000,
        sentiment: 'positive',
        mediaType: 'news',
      },
    ],
    'Competitor Product Launches': [
      {
        id: '3-1',
        source: 'TechCrunch',
        author: 'Alex Rivera',
        timestamp: '20m ago',
        title: 'New Product Announcement Shakes Up Market',
        content: 'A surprise product launch from a major competitor is drawing attention and could impact market share in the coming months.',
        reach: 112000,
        sentiment: 'neutral',
        mediaType: 'news',
      },
      {
        id: '3-2',
        source: 'The Verge',
        author: 'Chris Martinez',
        timestamp: '1h ago',
        title: 'Hands-on: First Look at Latest Innovation',
        content: 'Our first impressions of the newly announced device suggest it could be a game-changer for the industry.',
        reach: 87000,
        sentiment: 'positive',
        mediaType: 'news',
      },
      {
        id: '3-3',
        source: 'r/technology',
        subreddit: 'r/technology',
        author: 'u/techanalyst99',
        timestamp: 'Today · 10:30 AM',
        title: "Competitor's New Product Launch Gets Mixed Reception",
        content: 'Lots of discussion around the new product launch announcement. The product looks solid but pricing concerns are dominating the discourse in tech circles.',
        reach: 18600,
        sentiment: 'neutral',
        mediaType: 'reddit',
        platform: 'Reddit',
        keyword: 'product launch',
        views: 421,
      },
      {
        id: '3-4',
        source: 'Wired',
        author: 'Nina Patel',
        timestamp: '4h ago',
        title: 'Product Comparison: How New Entries Stack Up',
        content: 'We compare the latest product releases across key metrics to help you understand the competitive landscape.',
        reach: 45000,
        sentiment: 'neutral',
        mediaType: 'news',
      },
    ],
    'Social Backlash Monitoring': [
      {
        id: '4-1',
        source: 'TechWatch',
        handle: '@techwatch',
        timestamp: 'Today · 5:05 PM',
        content: 'Growing concerns about the latest policy changes. Users are expressing frustration with the new terms of service. This level of backlash is unprecedented. #TechNews',
        reach: 23000,
        sentiment: 'negative',
        mediaType: 'social',
        platform: 'X',
        country: 'US',
        keyword: 'policy',
        likes: 45,
        views: 892,
      },
      {
        id: '4-2',
        source: 'r/technology',
        subreddit: 'r/technology',
        author: 'u/industryinsider',
        timestamp: 'Today · 4:35 PM',
        title: 'Community Response to Announcement Has Been Overwhelmingly Negative',
        content: 'Many are calling for more transparency from leadership. The community backlash is growing louder by the hour, with thousands of comments calling for a policy reversal.',
        reach: 15000,
        sentiment: 'negative',
        mediaType: 'reddit',
        platform: 'Reddit',
        keyword: 'backlash',
        views: 1203,
      },
      {
        id: '4-3',
        source: 'BrandCritic',
        handle: '@brandcritic',
        timestamp: 'Today · 4:00 PM',
        content: 'Another day, another PR crisis brewing. Companies need to do better at listening to customer feedback before things spiral out of control. #BrandFail',
        reach: 8500,
        sentiment: 'negative',
        mediaType: 'social',
        platform: 'X',
        keyword: 'PR crisis',
        likes: 8,
        views: 203,
      },
    ],
  };

  // Default feed items for searches not in templates
  const defaultItems: FeedItem[] = [
    {
      id: 'default-1',
      source: 'Industry News',
      author: 'Staff Reporter',
      timestamp: '30m ago',
      title: `Latest Updates on ${searchName}`,
      content: 'Stay informed with the latest developments and analysis from our expert team covering this topic.',
      reach: 45000,
      sentiment: 'neutral',
    },
    {
      id: 'default-2',
      source: 'Market Watch',
      author: 'Analysis Team',
      timestamp: '2h ago',
      title: 'Trends and Insights',
      content: 'Our comprehensive analysis reveals key patterns and emerging trends that could impact your strategy.',
      reach: 32000,
      sentiment: 'positive',
    },
    {
      id: 'default-3',
      source: 'Daily Report',
      author: 'Editorial',
      timestamp: '5h ago',
      title: 'Weekly Roundup',
      content: 'A summary of the most important stories and developments from the past week.',
      reach: 28000,
      sentiment: 'neutral',
    },
  ];

  return feedTemplates[searchName] || defaultItems;
};

export const initialCanvases: MonitorCanvas[] = [
  {
    id: 'canvas-1',
    name: 'Brand Monitoring',
    streams: [
      {
        id: 'stream-1',
        name: 'Brand Mentions',
        searchId: '1',
        searchName: 'Brand + Earnings Risk',
        items: generateFeedItems('Brand + Earnings Risk'),
      },
      {
        id: 'stream-2',
        name: 'Leadership News',
        searchId: '3',
        searchName: 'Executive Leadership Coverage',
        items: generateFeedItems('Executive Leadership Coverage'),
      },
    ],
  },
  {
    id: 'canvas-2',
    name: 'Competitive Intel',
    streams: [
      {
        id: 'stream-3',
        name: 'Product Launches',
        searchId: '8',
        searchName: 'Competitor Product Launches',
        items: generateFeedItems('Competitor Product Launches'),
      },
      {
        id: 'stream-4',
        name: 'Social Sentiment',
        searchId: '7',
        searchName: 'Social Backlash Monitoring',
        items: generateFeedItems('Social Backlash Monitoring'),
      },
    ],
  },
];

export { generateFeedItems };
