import { Alert } from './types';

export const mockAlerts: Alert[] = [
  {
    id: 'alert-1',
    type: 'spike_detection',
    source: 'Brand Mentions Search',
    title: 'Unusual spike detected',
    description: '847 mentions in the last hour vs. 120 average',
    timestamp: '2m ago',
    isRead: false,
    metadata: {
      searchName: 'Brand Mentions',
      mentionCount: 847,
    },
  },
  {
    id: 'alert-2',
    type: 'sentiment_shift',
    source: 'Product Launch Campaign',
    title: 'Sentiment shifted to positive',
    description: 'Overall sentiment changed from neutral to positive (78%)',
    timestamp: '15m ago',
    isRead: false,
    metadata: {
      searchName: 'Product Launch',
      sentimentFrom: 'neutral',
      sentimentTo: 'positive',
    },
  },
  {
    id: 'alert-3',
    type: 'top_reach',
    source: 'Industry News Search',
    title: 'Wall Street Journal mention',
    description: 'Major coverage in WSJ with estimated reach of 2.4M',
    timestamp: '32m ago',
    isRead: false,
    metadata: {
      searchName: 'Industry News',
      reach: 2400000,
    },
  },
  {
    id: 'alert-4',
    type: 'x_influencer',
    source: 'Competitor Monitoring',
    title: '@TechAnalyst posted about your search',
    description: 'High-influence account (1.2M followers) mentioned your brand',
    timestamp: '1h ago',
    isRead: true,
    metadata: {
      platform: 'X',
      reach: 1200000,
    },
  },
  {
    id: 'alert-5',
    type: 'company_events',
    source: 'Competitor Watch',
    title: 'Acquisition announced',
    description: 'Acme Corp announced acquisition of TechStartup Inc.',
    timestamp: '2h ago',
    isRead: true,
    metadata: {
      searchName: 'Competitor Watch',
    },
  },
  {
    id: 'alert-6',
    type: 'breakout_post',
    source: 'Social Monitoring',
    title: 'Breakout post detected',
    description: 'Facebook post reached 45K engagements vs. 2K weekly average',
    timestamp: '3h ago',
    isRead: true,
    metadata: {
      platform: 'Facebook',
      engagement: 45000,
    },
  },
  {
    id: 'alert-7',
    type: 'every_mention',
    source: 'CEO Mentions',
    title: 'New mention detected',
    description: 'Your CEO was mentioned in TechCrunch article',
    timestamp: '4h ago',
    isRead: true,
    metadata: {
      searchName: 'CEO Mentions',
    },
  },
  {
    id: 'alert-8',
    type: 'follow_post',
    source: 'Viral Post Tracker',
    title: 'New activity on followed post',
    description: '127 new replies and 89 reposts on tracked announcement',
    timestamp: '5h ago',
    isRead: true,
    metadata: {
      platform: 'X',
    },
  },
  {
    id: 'alert-9',
    type: 'industry_events',
    source: 'Market Intelligence',
    title: 'Regulatory change detected',
    description: 'New data privacy regulation announced affecting tech sector',
    timestamp: '6h ago',
    isRead: true,
  },
  {
    id: 'alert-10',
    type: 'rss_feed',
    source: 'Industry Blog Feed',
    title: 'New article published',
    description: '"The Future of AI in Media Monitoring" - Industry Insights Blog',
    timestamp: '8h ago',
    isRead: true,
  },
  {
    id: 'alert-11',
    type: 'likely_boosted',
    source: 'Competitor Social',
    title: 'Likely boosted post detected',
    description: 'Competitor Facebook post showing paid promotion patterns',
    timestamp: '12h ago',
    isRead: true,
    metadata: {
      platform: 'Facebook',
    },
  },
  {
    id: 'alert-12',
    type: 'page_engagement',
    source: 'Brand Facebook',
    title: 'High engagement day',
    description: 'Page engagement 340% above daily average',
    timestamp: '1d ago',
    isRead: true,
    metadata: {
      platform: 'Facebook',
      engagement: 340,
    },
  },
];
