import { SystemNotification } from './types';

export const mockNotifications: SystemNotification[] = [
  {
    id: 'notif-1',
    type: 'export_complete',
    title: 'Export complete',
    description: 'Your "Q4 Brand Report" PDF export is ready to download.',
    timestamp: '5m ago',
    isRead: false,
    actionLabel: 'Download',
  },
  {
    id: 'notif-2',
    type: 'share_received',
    title: 'Dashboard shared with you',
    description: 'Sarah Johnson shared "Competitor Analysis 2025" with you.',
    timestamp: '1h ago',
    isRead: false,
    actionLabel: 'View',
  },
  {
    id: 'notif-3',
    type: 'feature_announcement',
    title: 'New: AI-powered summaries',
    description: 'Generate instant summaries of your searches with our new AI feature.',
    timestamp: '3h ago',
    isRead: false,
    actionLabel: 'Try it',
  },
  {
    id: 'notif-4',
    type: 'report_ready',
    title: 'Weekly report generated',
    description: 'Your scheduled "Brand Health Weekly" report is ready.',
    timestamp: '6h ago',
    isRead: true,
    actionLabel: 'View report',
  },
  {
    id: 'notif-5',
    type: 'limit_warning',
    title: 'Approaching search limit',
    description: 'You\'ve used 85% of your monthly search quota.',
    timestamp: '1d ago',
    isRead: true,
    actionLabel: 'Upgrade',
  },
  {
    id: 'notif-6',
    type: 'team_invite',
    title: 'Team invitation',
    description: 'Michael Chen invited you to join the "PR Team" workspace.',
    timestamp: '1d ago',
    isRead: true,
    actionLabel: 'Accept',
  },
  {
    id: 'notif-7',
    type: 'integration_status',
    title: 'Slack integration connected',
    description: 'Your Slack workspace is now connected for alert delivery.',
    timestamp: '2d ago',
    isRead: true,
  },
  {
    id: 'notif-8',
    type: 'search_updated',
    title: 'Search auto-updated',
    description: '"Industry News" search was automatically updated with new sources.',
    timestamp: '3d ago',
    isRead: true,
  },
  {
    id: 'notif-9',
    type: 'maintenance',
    title: 'Scheduled maintenance complete',
    description: 'Platform maintenance has been completed successfully.',
    timestamp: '4d ago',
    isRead: true,
  },
  {
    id: 'notif-10',
    type: 'subscription_update',
    title: 'Subscription renewed',
    description: 'Your Enterprise plan has been renewed for another year.',
    timestamp: '1w ago',
    isRead: true,
  },
];
